version: 2

models:
  - name: dim_customer
    description: "Customer dimension table"
    columns:
      - name: customer_key
        description: "Surrogate key"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Business key from source"
        tests:
          - unique
          - not_null
      - name: email_address
        tests:
          - not_null

  - name: dim_product
    description: "Product dimension table"
    columns:
      - name: product_key
        tests:
          - unique
          - not_null
      - name: product_id
        tests:
          - unique
          - not_null
      - name: list_price
        tests:
          - not_null

  - name: dim_date
    description: "Date dimension table"
    columns:
      - name: date_key
        tests:
          - unique
          - not_null

  - name: fact_sales
    description: "Sales fact table"
    columns:
      - name: sales_key
        tests:
          - unique
          - not_null
      - name: date_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
      - name: customer_key
        tests:
          - relationships:
              to: ref('dim_customer')
              field: customer_key
      - name: product_key
        tests:
          - relationships:
              to: ref('dim_product')
              field: product_key